- name: Installing and running nginx
  hosts: web
  become: true
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Starting nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    

