- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
    - name: USERNAME
      prompt: Please enter your username
      private: false
    - name: PASSWORD
      prompt: please enter your password
      private: true
  tasks:
    - name: printing username and password
      ansible.builtin.debug:
        msg: Username is {{USERNAME}} and the password is {{PASSWORD}}