- name: demo on filtrs
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ANsible, terraform
    tagsmap:
      name: Ravi
      project: roboshop
      component: ansible
    
    tagslist:
      [
        {
            "key": "name",
            "value": "Ravi"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "ansible"
        }
      ]

  
  tasks:
  - name: Greeting
    ansible.builtin.debug:
      msg: "Hi Ravi, {{GREETING | default('Good Morning')}}"

  - name: string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: converting dict to list
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}"

  - name: converting list to dict
    ansible.builtin.debug:
      msg: "{{ tagslist | items2dict }}"